# Generated by Django 3.1.7 on 2021-03-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210226_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_on',
            field=models.BooleanField(default=False),
        ),
    ]
