# Generated by Django 3.1.7 on 2021-03-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_push_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Телефон'),
        ),
    ]
