# Generated by Django 3.1.7 on 2021-03-18 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210310_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(db_index=True)),
                ('code', models.IntegerField(db_index=True, verbose_name='Code')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Is checked')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2021, 3, 18, 0, 20), verbose_name='Expires at')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
    ]
