# Generated by Django 3.1.7 on 2021-05-04 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210430_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 0, 20), verbose_name='Expires at'),
        ),
    ]
