# Generated by Django 3.1.7 on 2021-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210505_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onesignal_token',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
