# Generated by Django 3.1.7 on 2021-05-10 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_onesignal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 10, 0, 20), verbose_name='Expires at'),
        ),
    ]
