# Generated by Django 3.1.7 on 2021-05-11 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210510_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 11, 0, 20), verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='onesignal_token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
