# Generated by Django 3.1.7 on 2021-03-03 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        ('users', '0002_auto_20210226_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('request_date', models.DateField(verbose_name='date')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='city', to='info.city')),
                ('containter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='container', to='info.container')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='line', to='info.line')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='city_proposition', to='info.city')),
                ('containter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='container_proposition', to='info.container')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='line_proposition', to='info.line')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_proposition', to='users.user')),
            ],
        ),
    ]
