# Generated by Django 3.1.7 on 2021-03-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        ('users', '0009_auto_20210310_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='amount')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('city', models.ManyToManyField(blank=True, null=True, related_name='cities', to='info.City')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='info.container')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line', to='info.line')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='amount')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_proposition', to='info.city')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_proposition', to='info.container')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_proposition', to='info.line')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_proposition', to='users.user')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кол-во')),
                ('handshake_time', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_deal', to='info.city')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_deal', to='info.container')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_deal', to='info.line')),
                ('user_proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_user_proposition', to='users.user')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_user_request', to='users.user')),
            ],
            options={
                'ordering': ['-handshake_time'],
            },
        ),
    ]
