# Generated by Django 3.1.7 on 2021-03-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproposition',
            old_name='containter',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='userrequest',
            old_name='containter',
            new_name='container',
        ),
    ]
