# Generated by Django 3.1.7 on 2021-03-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproposition',
            name='status',
            field=models.CharField(choices=[('1', 'в работе'), ('2', 'в архиве'), ('3', 'удален')], default='в работе', max_length=20),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='status',
            field=models.CharField(choices=[('1', 'в работе'), ('2', 'в архиве'), ('3', 'удален')], default='в работе', max_length=20),
        ),
    ]
