# Generated by Django 3.1.7 on 2021-03-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210226_1449'),
        ('info', '0001_initial'),
        ('containers', '0002_auto_20210303_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproposition',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_proposition', to='info.city'),
        ),
        migrations.AlterField(
            model_name='userproposition',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_proposition', to='info.container'),
        ),
        migrations.AlterField(
            model_name='userproposition',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_proposition', to='info.line'),
        ),
        migrations.AlterField(
            model_name='userproposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_proposition', to='users.user'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='info.city'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container', to='info.container'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='info.line'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кол-во')),
                ('handshake_time', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_deal', to='info.city')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_deal', to='info.container')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_deal', to='info.line')),
                ('user_proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_user_proposition', to='users.user')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_user_request', to='users.user')),
            ],
        ),
    ]
