# Generated by Django 3.1.7 on 2021-03-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_auto_20210304_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproposition',
            name='end_date',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='end_date',
            field=models.DateField(default='2020-03-05', verbose_name='end date'),
            preserve_default=False,
        ),
    ]
