# Generated by Django 3.1.7 on 2021-03-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('containers', '0003_auto_20210315_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='cities', to='info.City'),
        ),
    ]
