# Generated by Django 3.1.7 on 2021-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0003_auto_20210312_1053'),
        ('containers', '0004_auto_20210316_1239'),
    ]

    operations = [
    ]
