# Generated by Django 3.1.7 on 2021-03-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('containers', '0004_auto_20210305_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproposition',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='userproposition',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_proposition', to='info.city'),
        ),
        migrations.AlterField(
            model_name='userproposition',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_proposition', to='info.container'),
        ),
        migrations.AlterField(
            model_name='userproposition',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_proposition', to='info.line'),
        ),
        migrations.AlterField(
            model_name='userproposition',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='info.city'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='info.container'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line', to='info.line'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
