# Generated by Django 3.1.7 on 2021-04-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_auto_20210318_1406'),
        ('containers', '0005_merge_20210317_1154'),
    ]

    operations = [
    ]
