# Generated by Django 3.1.7 on 2021-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_auto_20210309_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproposition',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
    ]
