# Generated by Django 3.1.7 on 2021-04-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0006_merge_20210412_0635'),
        ('containers', '0006_merge_20210412_0519'),
    ]

    operations = [
    ]
