# Generated by Django 3.1.7 on 2021-04-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('users', '0012_auto_20210420_1617'),
        ('containers', '0008_auto_20210414_1804'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproposition',
            unique_together={('user', 'amount', 'city', 'line', 'container')},
        ),
        migrations.AlterUniqueTogether(
            name='userrequest',
            unique_together={('user', 'amount', 'line', 'container')},
        ),
    ]
