# Generated by Django 3.1.7 on 2021-04-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0009_auto_20210420_1617'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproposition',
            unique_together=set(),
        ),
    ]
