# Generated by Django 3.1.7 on 2021-04-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0010_auto_20210420_1646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrequest',
            unique_together=set(),
        ),
    ]
