# Generated by Django 3.1.7 on 2021-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0012_userproposition_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproposition',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='amount',
            field=models.IntegerField(default='0', verbose_name='amount'),
            preserve_default=False,
        ),
    ]
