# Generated by Django 3.1.7 on 2021-05-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('containers', '0013_auto_20210505_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproposition',
            name='city',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_proposition', to='info.city'),
        ),
        migrations.AlterField(
            model_name='userproposition',
            name='container',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='container_proposition', to='info.container'),
        ),
        migrations.AlterField(
            model_name='userproposition',
            name='line',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line_proposition', to='info.line'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='city',
            field=models.ManyToManyField(blank=True, default=1, related_name='cities', to='info.City'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='container',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='info.container'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='line',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line', to='info.line'),
        ),
    ]
