# Generated by Django 3.1.7 on 2021-03-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0004_auto_20210316_1239'),
        ('users', '0009_auto_20210310_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('first_mark', models.BooleanField(default=False)),
                ('second_mark', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.user')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to='users.user')),
                ('proposition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposition_chat', to='containers.userproposition')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_chat', to='containers.userrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Send datetime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='chat.room', verbose_name='Chat room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-date'],
            },
        ),
    ]
