# Generated by Django 3.1.7 on 2021-03-16 11:59

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210316_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, null=True, verbose_name='Send datetime'),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
