# Generated by Django 3.1.7 on 2021-05-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20210430_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='proposition_user_readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='request_user_readed',
            field=models.BooleanField(default=False),
        ),
    ]
